### ISSUE TITLE
line 676: syntax error near unexpected token 'cava'

### ISSUE THREAD

**Issue by ondrish** [JaKooLit/Hyprland-v3#13]
hello, I tried running the installation script, but when at step "copy config and wallpaper files" i get error msg from subject. 

it is on a fresh arch install. 

could you advise please? thank you in advance :)

**Comment by JaKooLit** [comment]
thanks for letting me know. I have corrected the script.

here's step for you to do

change directory to downloaded repo
cd Hyprland-v3
rm -r install-hyprland-v3
git pull
chmod +x install-hyprland-v3
./intall-hyprland-v3

do the installation again then it should be fine

alternative:

cd Hyprland-v3
mkdir -p ~/.config
cp -r config/* ~/.config/
chmod +× ~/.config/hypr/scripts/*
mkdir -p ~/Pictures/wallpapers
cp -r wallpapers ~/Pictures/



if youre overwhelmed by alternative, better just carry out the first step

**Comment by ondrish** [comment]
fixed, thank you :)
