### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by WoltEye** [JaKooLit/Hyprland-v3#18]
After the prompt ”would you like to copy config and wallpaper files?” If I press y or n it throws an error.
 ./install-hyprland-v3: line 729: syntax error near unexpected token (

**Comment by JaKooLit** [comment]
Thanks. Corrected

cd Hyprland-v3
rm -r install-hyprland-v3
git pull
chmod +× install-hyprland-v3
./install-hyprland-v3
