### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by g4ti0r** [JaKooLit/Hyprland-v3#2]
I have installed it.
After the installation is complete, reboot
Then I try to log in. When I enter the password and press Enter, it shows me the login page again.
And loop.

I don't have an NVIDIA .
AMD R7 4800U
16G
Vmware

**Comment by JaKooLit** [comment]
Did you enable 3d acceleration? 

Take note Hyprland is not designed to ran on a virtual environment, vmware included. 

In any case, ctrl alt f2 or f3 to bring up tty

log in as usual, type Hyprland if it does not start, 3d acceleration

It may ran but its very laggy and performance is shite

https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm
