### ISSUE TITLE
udpate 'hyprland-nvidia-git' to 'hyprland-nvidia'

### ISSUE THREAD

**Issue by ogios** [JaKooLit/Hyprland-v3#20]
`hyprland-nvidia-git` is still at `0.27`, but `hyprland-nvidia` is updated to `0.29` now

**Comment by JaKooLit** [comment]
its a git package so any changes on the main hyprland github repo will be reflected to it. All the packages in AUR with -git are updated automatically or any changes in upstream repos are updated once you install it

The hyprland-nvidia is a bin packages packed by maintainer
