### ISSUE TITLE
Missing Icon in Light Theme: network-wired.svg

### ISSUE THREAD

**Issue by skinner12** [JaKooLit/Hyprland-v3#22]
## Description:
I have installed Hyprland-v3 theme and in the light version I noticed that an important icon, "network-wired.svg," is missing. Upon checking the theme's repository, it appears that the link used to create the icon is also missing. Additionally, I have noticed that there might be other missing icons.

### Additional Details:

Steps to Reproduce the Issue:
- Install the "Hyprland-v3" theme in the light version.
- Observe that the "network-wired.svg" icon is missing.
- Check the theme repository to confirm the missing link.

### Waybar Error:
I would also like to report an error related to Waybar:
```
[error] Item 'nm-applet': Could not find an icon named 'nm-device-wired' and no pixmap given.
```

This error message is displayed in Waybar when run from console, and it appears to be related to the missing "nm-device-wired" icon.

**Comment by JaKooLit** [comment]
do you have network-manager installed and running?

If you dont use network manager, you can just remove or put the # before the 
exec-once = nm-applet --indicator & in the ~/.config/hypr/configs/Execs.conf

**Comment by skinner12** [comment]
Yes I use it and my waybar can't show that icon.

**Comment by JaKooLit** [comment]
I saw that there was an update on the icon themes. You could install it yourself 

https://www.gnome-look.org/p/1633305

Bear in my mind that nm-applet is on tray waybar modules so if other appears (blueman-applet for example) shows then it must be nm-applet issue only and not waybar

ensure network-manager-applet is installed on your system as well

https://archlinux.org/packages/extra/x86_64/network-manager-applet/

**Comment by skinner12** [comment]
Yes, the problem is from that source tar file. It doesn't have the icon for network. Anyway thank for your support, I'll replace it with something icon similar.

**Comment by JaKooLit** [comment]
if youre sure that its missing for source, you may want to open an issue on his github page

https://github.com/L4ki/Shiny-Plasma-Themes

however, I have now tried shiny-light-icons and I dont have issue with it

**Comment by skinner12** [comment]
I’ve downloaded the file you linked but I didn’t find it.
Il 8 set 2023, 17:36 +0200, Ja.KooLit ***@***.***>, ha scritto:

**Comment by JaKooLit** [comment]
if thats the case then its more on the icon dev page and not on mine
