### ISSUE TITLE
waybar style missing dark css

### ISSUE THREAD

**Issue by devudopw** [JaKooLit/Hyprland-v3#23]
When execute waybar style-change, but style-dark.css is missing.

**Comment by JaKooLit** [comment]
Im guessing you didnt choose to install GTK themes?

The install script will choose the dark waybar styles depending on the GTK theme selected during installation.

Anyway, there are 2 dark style css..

located in ~/.config/hypr/waybar/style/dark-styles

you can copy either one of those

i.e.
cp ~/.config/hypr/waybar/style/dark-styles/style-dark-cat.css ~/.config/hypr/waybar/style/style-dark.css

**Comment by JaKooLit** [comment]
anyway, I have adjust the script so in the future, wont happen again

thanks for the heads up

https://github.com/JaKooLit/Hyprland-v3/commit/72a17e48d8c2e2bcfcd236dbeb3676a4f3ea30c3
