### ISSUE TITLE
Discord keeps crashing

### ISSUE THREAD

**Issue by sclewis90** [JaKooLit/Hyprland-v3#26]
When I try and open Discord it crashes and I am logged out. How do I fix this?

**Comment by JaKooLit** [comment]
not sure if you are still using v3 or moved to new install script

if you are using v3, sorry wont fix

if not, you can open issues here

![Screenshot_21-Apr_01-58-18_30277](https://github.com/JaKooLit/Hyprland-v3/assets/85185940/1e858845-a93f-4074-bffa-debfdafa72a2)

Hyprland-Dots github page
https://github.com/JaKooLit/Hyprland-Dots
