### ISSUE TITLE
Laptop screen stays disabled after external monitor is disconnected

### ISSUE THREAD

**Issue by KaNuckles** [JaKooLit/Hyprland-v3#3]

**Comment by JaKooLit** [comment]
this is more like hyprland issue. Report it to Hyprland github
https://github.com/hyprwm/Hyprland/issues

plus, you dont even tell more about it. Did you close lid, did you manually disable a monitor or something

and also, they only one dealing lid switch on my config is

bindl=,switch:Lid Switch, exec, $LidSwitch

try to delete this line or put # before it

its on

~/.config/hypr/configs/keybinds.conf

line 88
