### ISSUE TITLE
(SOLVED) the waybar do not show up

### ISSUE THREAD

**Issue by Fluxy05** [JaKooLit/Hyprland-v3#4]
i have install hyperland v3 on a existent arch setup everything work fine exept for the waybar, i simply dont have any waybar
please can you help me with that ? thx a lot

**Comment by JaKooLit** [comment]
try to start manually
open foot (super enter)

cd ~/.config/hypr/scripts

./Waybar.sh

look for errors. 

if errors says cannot find waybar, need to reinstall waybar

paru or yay -S waybar-hyprland-git

once installed,

either manually start waybar or press super shit w to "restart" waybar.

If all ok, it should be then you can just log out and log in or reboot

**Comment by Fluxy05** [comment]
its working thx you
(ps : the waybar are beautiful)
