### ISSUE TITLE
right click act weird

### ISSUE THREAD

**Issue by Fluxy05** [JaKooLit/Hyprland-v3#5]
when i use the right mouse buton it act the same as the left, i have take a look into the hyperland.conf but i found nothing about it

**Comment by JaKooLit** [comment]
I have not set anything special regarding right or left click apart from dragging and resizing windows which is located in

~/.config/hypr/configs/Keybinds.conf

if you are using laptop touchpad, right click is 2 fingers on bottom right

**Comment by Fluxy05** [comment]
oh yeah i use touchpad and it work thx

**Comment by JaKooLit** [comment]
> oh yeah i use touchpad and it work thx

great. 3 fingers for swipe to left or right workspaces

**Comment by JaKooLit** [comment]
hey just additional. Found the fix thanks to Lucy_sweets

edit your hyprland.conf located in ~/.config/hypr/

line 46
change to clickfinger_behavior=0

then right click should work on bottom right corner of your touchpad
